[build]
  publish = "public"

[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
